import type { CentroSalud, Especialidad, Profesional, Turno, ConsultaMedica, User } from '@/types';

export const MOCK_CENTROS: CentroSalud[] = [
  {
    id: 'c1',
    nombre: 'Hospital Provincial Aurelio Crespo',
    tipo: 'HOSPITAL',
    direccion: 'Av. Juan Domingo Perón 450, Cruz del Eje',
    telefono: '03549-422111',
    ciudad: 'Cruz del Eje',
    horarioAtencion: '24 Horas (Guardia permanente)',
    disponibleGuardia: true,
  },
  {
    id: 'c2',
    nombre: 'Dispensario Municipal San Pantaleón',
    tipo: 'DISPENSARIO',
    direccion: 'Barrio Centro, Calle San Martín 820, Cruz del Eje',
    telefono: '03549-423500',
    ciudad: 'Cruz del Eje',
    horarioAtencion: 'Lunes a Viernes 07:00 a 19:00',
    disponibleGuardia: false,
  },
  {
    id: 'c3',
    nombre: 'Clínica Privada Cruz del Eje',
    tipo: 'CLINICA',
    direccion: 'Sarmiento 340, Cruz del Eje',
    telefono: '03549-421880',
    ciudad: 'Cruz del Eje',
    horarioAtencion: 'Lunes a Sábados 08:00 a 20:00',
    disponibleGuardia: true,
  },
  {
    id: 'c4',
    nombre: 'Consultorios Médicos del Valle',
    tipo: 'CONSULTORIO_PRIVADO',
    direccion: 'Mitre 125, Cruz del Eje',
    telefono: '03549-424010',
    ciudad: 'Cruz del Eje',
    horarioAtencion: 'Lunes a Viernes 09:00 a 18:00',
    disponibleGuardia: false,
  },
];

export const MOCK_ESPECIALIDADES: Especialidad[] = [
  { id: 'e1', nombre: 'Clínica Médica / Medicina General', descripcion: 'Atención primaria y control integral de la salud.' },
  { id: 'e2', nombre: 'Pediatría', descripcion: 'Cuidado y seguimiento médico infantil y adolescentes.' },
  { id: 'e3', nombre: 'Cardiología', descripcion: 'Prevención, diagnóstico y tratamiento de afecciones cardíacas.' },
  { id: 'e4', nombre: 'Traumatología y Ortopedia', descripcion: 'Lesiones óseas, articulares y musculares.' },
  { id: 'e5', nombre: 'Ginecología y Obstetricia', descripcion: 'Salud reproductiva y controles periódicos.' },
  { id: 'e6', nombre: 'Oftalmología', descripcion: 'Salud visual y graduación óptica.' },
  { id: 'e7', nombre: 'Dermatología', descripcion: 'Cuidado y tratamiento de afecciones de la piel.' },
];

export const MOCK_PROFESIONALES: Profesional[] = [
  {
    id: 'p1',
    nombre: 'Carlos',
    apellido: 'Bustos',
    matricula: 'MP-34982',
    especialidadId: 'e1',
    especialidadNombre: 'Clínica Médica / Medicina General',
    centrosSaludIds: ['c1', 'c2'],
    diasAtencion: ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes'],
    duracionTurnoMin: 20,
  },
  {
    id: 'p1_2',
    nombre: 'Laura',
    apellido: 'Fernández',
    matricula: 'MP-37120',
    especialidadId: 'e1',
    especialidadNombre: 'Clínica Médica / Medicina General',
    centrosSaludIds: ['c1', 'c3', 'c4'],
    diasAtencion: ['Lunes', 'Miércoles', 'Viernes'],
    duracionTurnoMin: 20,
  },
  {
    id: 'p2',
    nombre: 'Mariana',
    apellido: 'Gómez',
    matricula: 'MP-29140',
    especialidadId: 'e2',
    especialidadNombre: 'Pediatría',
    centrosSaludIds: ['c1', 'c3'],
    diasAtencion: ['Lunes', 'Miércoles', 'Viernes'],
    duracionTurnoMin: 30,
  },
  {
    id: 'p2_2',
    nombre: 'Esteban',
    apellido: 'Quiroga',
    matricula: 'MP-40291',
    especialidadId: 'e2',
    especialidadNombre: 'Pediatría',
    centrosSaludIds: ['c2', 'c4'],
    diasAtencion: ['Martes', 'Jueves', 'Sábados'],
    duracionTurnoMin: 25,
  },
  {
    id: 'p3',
    nombre: 'Fernando',
    apellido: 'López',
    matricula: 'MP-41203',
    especialidadId: 'e3',
    especialidadNombre: 'Cardiología',
    centrosSaludIds: ['c1', 'c3', 'c4'],
    diasAtencion: ['Martes', 'Jueves'],
    duracionTurnoMin: 30,
  },
  {
    id: 'p3_2',
    nombre: 'Gonzalo',
    apellido: 'Benítez',
    matricula: 'MP-36840',
    especialidadId: 'e3',
    especialidadNombre: 'Cardiología',
    centrosSaludIds: ['c1', 'c3'],
    diasAtencion: ['Lunes', 'Viernes'],
    duracionTurnoMin: 30,
  },
  {
    id: 'p4',
    nombre: 'Romina',
    apellido: 'Soria',
    matricula: 'MP-38419',
    especialidadId: 'e5',
    especialidadNombre: 'Ginecología y Obstetricia',
    centrosSaludIds: ['c2', 'c3'],
    diasAtencion: ['Lunes', 'Jueves', 'Viernes'],
    duracionTurnoMin: 25,
  },
  {
    id: 'p4_2',
    nombre: 'Florencia',
    apellido: 'Medina',
    matricula: 'MP-42890',
    especialidadId: 'e5',
    especialidadNombre: 'Ginecología y Obstetricia',
    centrosSaludIds: ['c1', 'c4'],
    diasAtencion: ['Martes', 'Miércoles'],
    duracionTurnoMin: 25,
  },
  {
    id: 'p5',
    nombre: 'Matías',
    apellido: 'Albarracín',
    matricula: 'MP-33109',
    especialidadId: 'e4',
    especialidadNombre: 'Traumatología y Ortopedia',
    centrosSaludIds: ['c1', 'c3'],
    diasAtencion: ['Lunes', 'Miércoles', 'Viernes'],
    duracionTurnoMin: 20,
  },
  {
    id: 'p5_2',
    nombre: 'Claudio',
    apellido: 'Guzmán',
    matricula: 'MP-39871',
    especialidadId: 'e4',
    especialidadNombre: 'Traumatología y Ortopedia',
    centrosSaludIds: ['c1', 'c4'],
    diasAtencion: ['Martes', 'Jueves'],
    duracionTurnoMin: 20,
  },
  {
    id: 'p6',
    nombre: 'Gabriel',
    apellido: 'Rossi',
    matricula: 'MP-31045',
    especialidadId: 'e6',
    especialidadNombre: 'Oftalmología',
    centrosSaludIds: ['c1', 'c3'],
    diasAtencion: ['Lunes', 'Martes', 'Jueves'],
    duracionTurnoMin: 20,
  },
  {
    id: 'p6_2',
    nombre: 'Silvina',
    apellido: 'Castro',
    matricula: 'MP-44120',
    especialidadId: 'e6',
    especialidadNombre: 'Oftalmología',
    centrosSaludIds: ['c3', 'c4'],
    diasAtencion: ['Miércoles', 'Viernes'],
    duracionTurnoMin: 25,
  },
  {
    id: 'p7',
    nombre: 'Andrea',
    apellido: 'Montiel',
    matricula: 'MP-35610',
    especialidadId: 'e7',
    especialidadNombre: 'Dermatología',
    centrosSaludIds: ['c2', 'c3', 'c4'],
    diasAtencion: ['Lunes', 'Miércoles'],
    duracionTurnoMin: 20,
  },
  {
    id: 'p7_2',
    nombre: 'Rodrigo',
    apellido: 'Sosa',
    matricula: 'MP-45230',
    especialidadId: 'e7',
    especialidadNombre: 'Dermatología',
    centrosSaludIds: ['c1', 'c3'],
    diasAtencion: ['Martes', 'Jueves', 'Viernes'],
    duracionTurnoMin: 25,
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u-paciente-1',
    nombre: 'Lucas',
    apellido: 'Ramírez',
    email: 'lucas.ramirez@email.com',
    dni: '38123456',
    telefono: '3549-551122',
    rol: 'PACIENTE',
  },
  {
    id: 'u-medico-1',
    nombre: 'Dr. Carlos',
    apellido: 'Bustos',
    email: 'carlos.bustos@esu.salud.gob.ar',
    dni: '27456789',
    telefono: '3549-401122',
    rol: 'MEDICO',
    matricula: 'MP-34982',
    especialidad: 'Clínica Médica / Medicina General',
  },
  {
    id: 'u-recep-1',
    nombre: 'Valeria',
    apellido: 'Peralta',
    email: 'valeria.recepcion@esu.salud.gob.ar',
    dni: '34999888',
    telefono: '3549-420000',
    rol: 'RECEPCIONISTA',
    centroSaludId: 'c1',
  },
  {
    id: 'u-admin-1',
    nombre: 'Administrador',
    apellido: 'ESU',
    email: 'admin@esu.salud.gob.ar',
    dni: '30111222',
    telefono: '3549-423000',
    rol: 'ADMIN',
  },
];

export const MOCK_TURNOS: Turno[] = [
  {
    id: 't-101',
    codigoVerificacion: 'ESU-2026-9812',
    fecha: new Date().toISOString().split('T')[0],
    hora: '08:30',
    pacienteId: 'u-paciente-1',
    pacienteNombre: 'Lucas Ramírez',
    pacienteDni: '38123456',
    pacienteTelefono: '3549-551122',
    obraSocial: 'APROSS',
    profesionalId: 'p1',
    profesionalNombre: 'Dr. Carlos Bustos',
    especialidadNombre: 'Clínica Médica / Medicina General',
    centroSaludId: 'c1',
    centroSaludNombre: 'Hospital Provincial Aurelio Crespo',
    estado: 'EN_ESPERA',
    motivoConsulta: 'Control de presión arterial y análisis periódicos.',
    fechaCreacion: '2026-09-20',
  },
  {
    id: 't-102',
    codigoVerificacion: 'ESU-2026-9813',
    fecha: new Date().toISOString().split('T')[0],
    hora: '09:00',
    pacienteId: 'u-paciente-2',
    pacienteNombre: 'María Celeste Vega',
    pacienteDni: '40112233',
    pacienteTelefono: '3549-447788',
    obraSocial: 'PAMI',
    profesionalId: 'p1',
    profesionalNombre: 'Dr. Carlos Bustos',
    especialidadNombre: 'Clínica Médica / Medicina General',
    centroSaludId: 'c1',
    centroSaludNombre: 'Hospital Provincial Aurelio Crespo',
    estado: 'CONFIRMADO',
    motivoConsulta: 'Dolor lumbar recurrente.',
    fechaCreacion: '2026-09-22',
  },
  {
    id: 't-103',
    codigoVerificacion: 'ESU-2026-7734',
    fecha: '2026-10-05',
    hora: '10:30',
    pacienteId: 'u-paciente-1',
    pacienteNombre: 'Lucas Ramírez',
    pacienteDni: '38123456',
    pacienteTelefono: '3549-551122',
    obraSocial: 'APROSS',
    profesionalId: 'p3',
    profesionalNombre: 'Dr. Fernando López',
    especialidadNombre: 'Cardiología',
    centroSaludId: 'c3',
    centroSaludNombre: 'Clínica Privada Cruz del Eje',
    estado: 'PENDIENTE',
    motivoConsulta: 'Electrocardiograma de rutina.',
    fechaCreacion: '2026-09-28',
  },
];

export const MOCK_CONSULTAS: ConsultaMedica[] = [
  {
    id: 'c-501',
    pacienteId: 'u-paciente-1',
    pacienteNombre: 'Lucas Ramírez',
    profesionalId: 'p1',
    profesionalNombre: 'Dr. Carlos Bustos',
    fecha: '2026-08-15',
    motivo: 'Cuadro gripal con fiebre de 38° y tos seca.',
    diagnostico: 'Infección de vías respiratorias superiores (J06.9)',
    tratamiento: 'Paracetamol 500mg cada 8hs, reposo e hidratación abundante.',
    signosVitales: {
      presionArterial: '120/80 mmHg',
      frecuenciaCardiaca: '74 lpm',
      temperatura: '38.1 °C',
      peso: '76 kg',
    },
    receta: {
      id: 'rec-901',
      codigoQR: 'QR-ESU-REC-901-VAL-2026',
      fechaEmision: '2026-08-15',
      fechaVencimiento: '2026-09-15',
      medicoNombre: 'Dr. Carlos Bustos',
      medicoMatricula: 'MP-34982',
      pacienteNombre: 'Lucas Ramírez',
      pacienteDni: '38123456',
      medicamentos: [
        {
          nombreComercial: 'Paracetamol',
          droga: 'Paracetamol',
          presentacion: 'Comprimidos 500mg',
          dosisIndicada: '1 comprimido cada 8 horas durante 5 días',
          cantidad: '1 caja x 20 comprimidos',
        },
      ],
      diagnostico: 'Infección de vías respiratorias superiores',
      indicacionesGenerales: 'Consultar si la fiebre persiste más de 72 horas.',
    },
  },
];
